### ISSUE TITLE
Clarify usage and formatting of Publication options

### ISSUE THREAD

**Issue by eugeneromero** [philips-software/post-to-medium-action#19]
Hey!

First off, thank you for creating this Action, I have been using it successfully to repost my personal blog articles on Medium.

A question that I think could be explained better in the docs: How should the `publication_name` and `publication_id` look like, and where can one find them?

I publish sometimes to a publication run by my company. I am not sure of the following especially:

1. Is the publication name its display name on Medium?
2. Is it instead the string in the URL after medium.com/ ?
3. Is that string the ID instead?
4. If not, where can one find the ID?
5. User IDs on Medium seem to start with an @. Is this true of the Publication ID also, and if so, should it be included when adding it to the Action?

The main reason behind these questions is that it is not so simple to test via trial and error, as the publication editor might get a bunch of notifications as I test out different options :D

Thank you for your help with this!

**Comment by Brend-Smits** [comment]
Heey @eugeneromero,
Thank you for using this Action. Glad you find it useful. 
These are great questions. The publication name can be retrieved by going to the publication URL. I found the URL by going to the company or person's publication and clicking on it. As an example, I created a test-publication-draft publication that can be found via the following URL: https://medium.com/test-brend-publication-draft
Everything after medium.com/ is the publication name in this case. This can also be found in the settings of the publication: 
![image](https://user-images.githubusercontent.com/15904543/150793717-0a234306-9cc8-4b28-9f37-e732f45fbdda.png)

So far I have not found a way to retrieve the publication id within the Medium UI. I use the API to achieve this. First I get my user ID:
```bash
curl --location --request GET 'https://api.medium.com/v1/me' \
--header 'Authorization: Bearer INTEGRATION_TOKEN_HERE'
```

Then I use the ID (this is the user id) in the response to retrieve a list of publications:
```bash
curl --location --request GET 'https://api.medium.com/v1/users/USER_ID_HERE/publications' \
--header 'Authorization: Bearer INTEGRATION_TOKEN_HERE'
```
Make sure to replace the USER_ID_HERE and INTEGRATION_TOKEN_HERE with the representative values.
In the future, I can make a quick bash script to make the retrieval of these attributes easier. 

What I did for Philips is test these things with my own token until I set up a proper workflow that works. When confirmed working, I switched the integration token and changed some variables in the settings (name, ids, etc).

I hope this helped. If not, please don't hesitate to ask for clarification.

**Comment by eugeneromero** [comment]
This is great info, and it clarifies the questions I had! Thank you for writing this detailed description. Maybe this stuff should be added/linked in the README?

Thanks again! I will close this issue now.
